id: PDE44157E
initial_creation_type: input
source_metadata:
  title: Ethical Guidelines
  language: en
  description: 'The following texts are currently available as part of our Ethical
    Guidelines series:'
  volume:
    0563ce3ec5264aff89fef8edc3395b48:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Abstention
    e0384a6b56fd4522a472cb89996d29fd:
      title: Song of Advice for Giving Up Meat Eating
      parent: Abstention
    a7cf6b409afb47019ae5848ff09d23da:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Behavioural Guidelines
    f6816b50b4874fc087c98a1f35ad319f:
      title: Drodung Monastery Guidelines
      parent: Behavioural Guidelines
    738a09801e8a45318d98286f01b942d5:
      title: 'The Pellucid Mirror: Behavioural Guidelines for the Saṅgha'
      parent: Behavioural Guidelines
    9c626442c63e477d88c3a5cdbf846b2e:
      title: 'The Seed of Benefit and Happiness: Behavioural Guidelines'
      parent: Behavioural Guidelines
    26c416d474bf4a9f974ca7b6051db183:
      title: A Plea to Those who Present ‘Red Offerings’ to Worldly Deities
      parent: Ethical Advice
    dc1c1e7dd6a6494a998b7cd63094162c:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Ethical Advice
created_at: '2022-03-01T03:40:18.760176'
last_modified_at: '2022-03-01T03:40:18.760182'
